#SPDX-License-Identifier: MIT-0
---
# handlers file for server_role_redis_server


- name: Reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded


- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted


